on:
    workflow_dispatch:
    schedule:
      - cron: "5 4 * * *"  # once a day
  
  jobs:
    clean:
      runs-on: ubuntu-latest
      name: Delete old test images
      steps:
        - uses: snok/container-retention-policy@v3.0.0
          with:
            account: user
            token: ${{ secrets.PAT }}
            image-names: "emoji-svc voting-svc web"
            image-tags: "sha-*"  # target any image that has a tag starting with the word test or dev
            cut-off: 12w
            dry-run: true